project:
  title: "Cours Paris 1"
  output-dir: _output
  type: website


website:
  title: "Cours de sondage"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
    right:
      - icon: github
        href: https://github.com
  page-navigation: true

toc: false
number-sections: false
bibliography: references.bib 

format:
  html:
    theme: yeti
    css: Sites/styles.css
    toc: true
  clean-revealjs:
      transition: slide
      smaller: true
      preview-links: true
      width: 1500
      margin: 0.05
      toc: false
      vertical: false

from: markdown+emoji
licence: CC BY-NC

editor: visual